import localFont from "next/font/local";
import "../globals.css";

import '@/styles/app.css';
import '@/styles/iconly.css';

import { Sidebar } from '@/components/Sidebar';


const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
      
                <main>
                    <div id="app">
                        <div id="sidebar">
                            <div className="sidebar-wrapper active">
                                <div className="sidebar-header position-relative">
                                    <div className="d-flex justify-content-between align-items-center">
                                        <div className="logo">
                                            <a href="index.html">

                                            </a>
                                        </div>

                                        <div className="sidebar-toggler x">
                                            <a href="#" className="sidebar-hide d-xl-none d-block">
                                                <i className="bi bi-x bi-middle" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <Sidebar />
                            </div>
                        </div>
                        <div id="main">
                            {children}
                        </div>
                    </div>
                </main>
           
    );
}
